### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by zhu2014yi** [ZekuiQin/SiamKPN#2]
你好，我想问一下这个算法训练你们是用了多少张gpu训练了多少时间？

**Comment by ZekuiQin** [comment]
we trained models over 5 GTX1080Ti GPUs with a total batch size of 80.
SiamKPN-1s spent about 1 day for training, and SiamKPN-3s spent about 1.5 days.

**Comment by zhu2014yi** [comment]
thanks
