### ISSUE TITLE
what‘s the keypoint refers to when a target is class-agnostic?

### ISSUE THREAD

**Issue by xxAna** [ZekuiQin/SiamKPN#3]
Thank you for your sharing! And I wonder what‘s the keypoint refers to when a target is class-agnostic? Does it the ceter point of a target. Please correct me if I am wrong. Thank you again for your sharing!

**Comment by ZekuiQin** [comment]
yes, the keypoint refers to center point of the tracking target.
Tracking is actually a two-class classify problem when the target is chose in the first frame of a video.

**Comment by ZekuiQin** [comment]
yes, the keypoint refers to the center point of the tracking target.
Tracking is actually a two-class classify problem when the target is chose in the first frame of a video.

**Comment by xxAna** [comment]
Get it. Thank you for your reply. ^^
