### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by suhwan-cho** [ZekuiQin/SiamKPN#4]
Hi, thanks for your great work!

Is it available to upload the pre-trained models on google drive or others using Eng format?

**Comment by laisimiao** [comment]
> Hi, thanks for your great work!
> 
> Is it available to upload the pre-trained models on google drive or others using Eng format?

tell me your google email address, i will share with you.

**Comment by suhwan-cho** [comment]
> > Hi, thanks for your great work!
> > Is it available to upload the pre-trained models on google drive or others using Eng format?
> 
> tell me your google email address, i will share with you.

Hi, thank you so much!
e-mail: chosuhwan@yonsei.ac.kr
