### ISSUE TITLE
How to crop LaSOT and GOT-10K to 511 resolution?

### ISSUE THREAD

**Issue by laisimiao** [ZekuiQin/SiamKPN#6]
Hello, thanks for  opening such an excellent work!
But I have a question: **How to crop LaSOT and GOT-10K to 511 resolution?**  
Because pysot just have no scripts to process `LaSOT and GOT-10K`.

**Comment by ZekuiQin** [comment]
Please refer to [pysot](https://github.com/STVIR/pysot)

**Comment by ZekuiQin** [comment]
Please refer to [pysot](https://github.com/STVIR/pysot)
